[versions]
agp = "8.9.3"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activity = "1.10.1"
androidx-appcompat = "1.7.1"
androidx-core = "1.17.0"
androidx-espresso = "3.7.0"
androidx-lifecycle = "2.9.3"
androidx-testExt = "1.3.0"
composeMultiplatform = "1.9.0-beta03"
junit = "4.13.2"
kotlin = "2.2.0"
ktor = "3.2.3"
coroutines = "1.10.2"
kotlinx-collections-immutable = "0.4.0"
graphics-shapes = "1.0.0-alpha09"
napier = "2.7.1"
koin = "4.1.1-Beta1"
ksp = "2.2.0-2.0.2"
androidxRoom = "2.7.2"
robolectric = "4.7.3"
test-manifest = "1.9.0"
androidx-test-junit = "1.3.0"
assertk = "0.28.1"
coil="3.3.0"
sqlite = "2.5.2"
materialNavigation = "1.8.0-beta02"
uiautomator = "2.3.0"
androidx-test-core="1.7.0"
androidx-material="1.12.0"
kotlinxDatetime = "0.7.1"
android-billing = "8.0.0"
material3 = "1.9.0-beta03"
navigation-androidx = "2.9.0-beta05"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-rules = { module = "androidx.test:rules", version.ref = "androidx-test-core" }
androidx-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "androidx-espresso" }
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
androidx-testExt-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-navigation = { name = "navigation-compose", group = "org.jetbrains.androidx.navigation", version.ref = "navigation-androidx" }
google-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "material3" }
graphics-shapes = { name = "graphics-shapes", group = "org.jetbrains.androidx.graphics", version.ref = "graphics-shapes" }
android-billing = { module = "com.android.billingclient:billing-ktx", version.ref = "android-billing" }
jetbrains-material-navigation = { module = "org.jetbrains.compose.material:material-navigation", version.ref = "materialNavigation" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }
#koin
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-test-junit4 = { module = "io.insert-koin:koin-test-junit4" }
koin-test-junit5 = { module = "io.insert-koin:koin-test-junit5" }

#ktor
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
#ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }

#Napier
napier = { module = "io.github.aakira:napier", version.ref = "napier" }

#room
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
#coil
coil-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coil" }
coil3-coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil3-coil-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }

#coroutines and kotlinx
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }

#Junit
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "test-manifest" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
androidx-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "test-manifest" }



[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
room = { id = "androidx.room", version.ref = "androidxRoom" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }